### ISSUE TITLE
Question about extensions

### ISSUE THREAD

**Issue by Shatur** [shadmansaleh/lualine.nvim#41]
I want to create an extension for [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui). But every window (watcher, breakpoints, stack and scopes) have a different filetype. Should I create a separate extensions for each filetype?

**Comment by shadmansaleh** [comment]
What do you want to show in statusline ?

**Comment by Shatur** [comment]
> If you want to display the same extension on all of them then you can have multiple entries in filetypes table.

I just want to display a buffer name.
`filetypes` is just what I need, thank you!

Will send a PR soon.

**Comment by shadmansaleh** [comment]
You can inline extensions in you config too
```lua
require'lualine'.setup{
  extensions = { 'fzf', 'quickfix', {
    sections = {
      lualine_a = { component1 },
      lualine_c = { component2 },
    },
  filetypes = { 'ft1', 'ft2',... }
}
```

Or if you put the extension file in any `&rtp/lua/lualine/extionsions/`
folder like In your config `~/.config/nvim/lua/lualine/extensions/` lualine will load the extension from there .

I'm saying this because 
> display a buffer name

Doesn't sound like it's dap-ui specific hanse feels like it'll make more sense in user config.

**Comment by Shatur** [comment]
Okay!
The main screenshot of `dap-ui` displays the names of the buffers, so I also want to do this for myself.
I think the author is using galaxyline which has a `short_line_list `function that allows you to specify such buffers.
