### ISSUE TITLE
Question about commit f2f014e

### ISSUE THREAD

**Issue by zeertzjq** [shadmansaleh/lualine.nvim#73]
The commit message of <https://github.com/shadmansaleh/lualine.nvim/commit/f2f014e3797576eccc2320b711a336ea95f448fd> says `transitional_highlight isn't created when both retrieval of fg or bg has failed`, but the code doesn't create transtional highlight when either of then failed. Is the code wrong?

ToggleTerm statusline fills the whole line when `Normal` doesn't have background:
![Screenshot_20210929_231042](https://user-images.githubusercontent.com/35768171/135297350-13699c7a-27f5-4b35-94cf-7358a6b81632.png)

And removing the following lines solves this:
<https://github.com/shadmansaleh/lualine.nvim/blob/05314de43aad9f1175a0e197eefcccf31973755c/lua/lualine/highlight.lua#L263-L265>

If the correct behavior is not to create transtional highlight when retrieval of both has failed, it is fine to just delete the three lines, as `bg == fg` already covers the case where both `bg` and `fg` are `nil`.

**Comment by shadmansaleh** [comment]
> but the code doesn't create transtional highlight when either of then failed. Is the code wrong?

The code is right but the commit message doesn't say it correctly. We need both  and bg to create transitional hl and also need both left and right hl to have different bg color . That's why the bg == fg check so don't create a trans_hl when both left & right hl is lualine_b for example.

> ToggleTerm statusline fills the whole line when Normal doesn't have background:

Not sure if I understand the issue correctly .Do you have a transparent background ? Does it only happen on ToggleTerm extension ?

https://github.com/shadmansaleh/lualine.nvim/blob/05314de43aad9f1175a0e197eefcccf31973755c/lua/lualine.lua#L142

This line should prevent it from happening by putting c sections hl before right sections(x/y/z) . What's the state of your lualine_c_{mode} hl groups are they some how related to Normal  ?

**Comment by zeertzjq** [comment]
> What's the state of your lualine_c_{mode} hl groups are they some how related to Normal?

No.

**Comment by zeertzjq** [comment]
It happens on chadtree extension as well. Both only have `lualine_a`.

**Comment by zeertzjq** [comment]
<https://github.com/shadmansaleh/lualine.nvim/blob/05314de43aad9f1175a0e197eefcccf31973755c/lua/lualine.lua#L139>
This line prevents it from c sections hl from being put after section a, as only section a is non-empty.

**Comment by shadmansaleh** [comment]
Ok I see those don't have anything in x/y/z sections . And intentionally it doesn't put %< and hl in that case( This was done so you could render one sections satuslines too )

A workaround will be to add a dummy component in x section

You can try this and see if it solves the issue.
```diff
  diff --git a/lua/lualine/extensions/toggleterm.lua b/lua/lualine/extensions/toggleterm.lua
index a9be001..76fc10a 100644
--- a/lua/lualine/extensions/toggleterm.lua
+++ b/lua/lualine/extensions/toggleterm.lua
@@ -5,10 +5,16 @@ local function toggleterm_statusline()
   return 'ToggleTerm #' .. vim.b.toggle_number
 end
 
+local empty = {
+  function() return ' ' end,
+  padding = 0,
+}
+
 local M = {}
 
 M.sections = {
   lualine_a = { toggleterm_statusline },
+  lualine_x = { empty },
 }
 
 M.filetypes = { 'toggleterm' }
```

I'm currently really busy . I'll try to patch other extension that similarly only uses just a/b/c section when I get time .
